// Code generated by go-bindata. (@generated) DO NOT EDIT.

// Package tlsConnection generated by go-bindata.// sources:
// server.key
// server.pem
package tlsConnection

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _serverKey = []byte(`-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIB3gknKMEKIJGh5a4M+NENb9rlr5NATyeCwYJtHDLCxhoAoGCCqGSM49
AwEHoUQDQgAEBudHmvUKQ7Q3EW01Dwbd/3jadTW8bvPu49NnYfjgD1k7cfsa27JK
pWabFclFETOWO0uBUS+o7wrP3RiQq8CZ3A==
-----END EC PRIVATE KEY-----
`)

func serverKeyBytes() ([]byte, error) {
	return _serverKey, nil
}

func serverKey() (*asset, error) {
	bytes, err := serverKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "server.key", size: 302, mode: os.FileMode(420), modTime: time.Unix(1600152045, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _serverPem = []byte(`-----BEGIN CERTIFICATE-----
MIIBzDCCAXICCQCmXj+YPpzLnDAKBggqhkjOPQQDAjBuMQswCQYDVQQGEwJaQTEQ
MA4GA1UECAwHR2F1dGVuZzETMBEGA1UEBwwKUm9vZGVwb29ydDEVMBMGA1UECgwM
Ymhib3NtYW4uY29tMSEwHwYJKoZIhvcNAQkBFhJiaGJvc21hbkBnbWFpbC5jb20w
HhcNMjAwOTE1MDY0MzU5WhcNMzAwOTEzMDY0MzU5WjBuMQswCQYDVQQGEwJaQTEQ
MA4GA1UECAwHR2F1dGVuZzETMBEGA1UEBwwKUm9vZGVwb29ydDEVMBMGA1UECgwM
Ymhib3NtYW4uY29tMSEwHwYJKoZIhvcNAQkBFhJiaGJvc21hbkBnbWFpbC5jb20w
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQG50ea9QpDtDcRbTUPBt3/eNp1Nbxu
8+7j02dh+OAPWTtx+xrbskqlZpsVyUURM5Y7S4FRL6jvCs/dGJCrwJncMAoGCCqG
SM49BAMCA0gAMEUCIBd3FPyP6qGi8/N5llSQhQXqAAWMo+GwPMsuAUP9DGW/AiEA
zyAU3MZxxfj/L/XFoG3ktFNdHiEr0cvUMxYaeO2EOC0=
-----END CERTIFICATE-----
`)

func serverPemBytes() ([]byte, error) {
	return _serverPem, nil
}

func serverPem() (*asset, error) {
	bytes, err := serverPemBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "server.pem", size: 684, mode: os.FileMode(420), modTime: time.Unix(1600152239, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"server.key": serverKey,
	"server.pem": serverPem,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("nonexistent") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"server.key": &bintree{serverKey, map[string]*bintree{}},
	"server.pem": &bintree{serverPem, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
