all: IConnectionReactorFactory


IConnectionReactorFactory:
	mockgen -package intf -generateWhat mockgen -destination IConnectionReactorFactoryMock.go . IConnectionReactorFactory,IConnectionReactor







