all:
	mockgen -package common -generateWhat mockgen -destination ConnMock.go net Conn,Addr
	mockgen -package common -generateWhat mockgen -destination IOnCreateConnectionMock.go . IOnCreateConnection







